version: '3.7'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: whatwewant/imgproxy:v0
    ports:
      - 0.0.0.0:9000:8080/tcp
    environment:
      PREFIX: /files
